spring:
  mvc:
    static-path-pattern: /static/**
    static-locations: classpath:/static/
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
